### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by DisplayedAim** [endreman0/Excalibot#1]
<img width="741" alt="screen shot 2018-09-08 at 5 26 37 am" src="https://user-images.githubusercontent.com/33333386/45239228-d8f79200-b327-11e8-87a1-fd41c99c92da.png">
I have installed all the requirements.

**Comment by thegranddev** [comment]
Make sure you installed all the requirements/dependencies. It looks like you're missing some. If not, make sure you're typing the correct command to install them. If not either, then the owner most likely forgot to put a requirement because im 99% sure this is a requirement error, correct me if i'm wrong. Also, use node.js :)

**Comment by endreman0** [comment]
Missing dependencies wouldn't cause this issue. Python distinguishes dependencies from arbitrary files, and this is an arbitrary file that happens to be missing. Creating a `logs` directory in the project root should fix the issue. (Also, show me a JS Discord library half as cool as discord.py first ;))

**Comment by thegranddev** [comment]
> Missing dependencies wouldn't cause this issue. Python distinguishes dependencies from arbitrary files, and this is an arbitrary file that happens to be missing. Creating a `logs` directory in the project root should fix the issue. (Also, show me a JS Discord library half as cool as discord.py first ;))


node.js is literally superior to all other programming languages

**Comment by tweirtx** [comment]
> node.js is literally superior to all other programming languages

...in what way?

**Comment by thegranddev** [comment]
name one thing node.js CANT do

**Comment by tweirtx** [comment]
run with low amounts of RAM

**Comment by endreman0** [comment]
Closing this issue; @DisplayedAim, if the fix I posted above doesn't work, feel free to reopen it.
